---
# tasks file for xfs-partition
- name: Installing packages to mount as xfs
  apt-get install -y xfsprogs

- name: Get list of block devices
  command: 'lsblk -lno NAME'
  register: results

- name: Create variable block_devices
  set_fact:
    block_devices: "{{ results.stdout_lines }}"

- debug:
    var: block_devices

- name: block_device
  prompt: Which block device to use?
  private: no

- name: Verifying disk is empty
  command: 'file -s {{block_device}}'
  register: results
  failed_when:  results.stdout_lines[0] != "data"

- name: Creating a partition
  command: 'fdisk {{block_device}}'

- name:  Formatting as xfs
  command: 'mkfs.xfs -f {{block_device}}'

- name:  Creating mount point directory
  file: path="{{mount_path}}" state=directory

- name: Mounting volume
  command: "mount -t xfs {{block_device}} {{mount_path}}"

# - name: Adding permissions to kafka directory
#   chown -R ubuntu:ubuntu {{mount_path}}

- name: Checking mount point is working
  command: "df -h {{mount_path}}"

- name: Configuring automount on start
  lineinfile:
    path: "/etc/fstab"
    line: "{{block_device}} {{mount_path}} xfs defaults 0 0"
    state: present
    backup: True

- name: Rebooting server to check if drive mounted
  reboot:
    reboot_timeout: 3600
