---
# tasks file for xfs-partition

- name: Checking mount point
  command: mountpoint -q {{mount_point}}
  register: volume_stat
  failed_when: False
  changed_when: False

- debug:
    msg: "It is a mountpoint!"
  when: volume_stat.rc == 0

- include_tasks: create_xfs.yml
  when: volume_stat.rc != 0
